#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

#
# CORE SEARCH PATH OPTIONS
#
homepath                  /storage/.config/mame
rompath                   /storage/roms/mame;/storage/roms/arcade;/storage/roms/bios
samplepath                /storage/roms/mame/samples;/storage/roms/arcade/samples
artpath                   /storage/roms/mame/artwork;/usr/share/mame/artwork
ctrlrpath                 /storage/.config/mame/ctrlr;/usr/share/mame/ctrlr
fontpath                  /usr/share/mame
cheatpath                 /storage/.config/mame/cheat
pluginspath               /usr/share/mame/plugins

#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             /storage/.config/mame/cfg
nvram_directory           /storage/.config/mame/nvram
input_directory           /storage/.config/mame/inp
state_directory           /storage/roms/savestates/mame
snapshot_directory        /storage/roms/screenshots
diff_directory            /storage/.config/mame/diff
comment_directory         /storage/.config/mame/comments
share_directory           /storage/.config/mame/share

#
# CORE MISC OPTIONS
#
skip_gameinfo             1

#
# SCRIPTING OPTIONS
#
plugins                   1
plugin                    hiscore

#
# OSD VIDEO OPTIONS
#
video                     opengl
window                    0
keepaspect                1
filter                    1
bgfx_path                 /usr/share/mame/bgfx

#
# OSD SOUND OPTIONS
#
sound                     sdl
